version: '3.8'

services:
  # PostgreSQL database (shared)
  postgres:
    image: postgres:15-alpine
    container_name: shared-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network
    ports:
      - "5432:5432"  # Optional: expose port for external access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # DBeaver CloudBeaver (Web-based database management)
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver-web
    restart: unless-stopped
    environment:
      - CB_SERVER_NAME=DBeaver Server
      - CB_ADMIN_NAME=${DBEAVER_ADMIN_USER:-admin}
      - CB_ADMIN_PASSWORD=${DBEAVER_ADMIN_PASSWORD}
    ports:
      - "8978:8978"  # Expose DBeaver on port 8978
    volumes:
      - dbeaver_workspace:/opt/cloudbeaver/workspace
      - dbeaver_config:/opt/cloudbeaver/conf
    networks:
      - postgres-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8978/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  postgres-network:
    name: postgres-network
    driver: bridge

volumes:
  postgres_data:
    driver: local
  dbeaver_workspace:
    driver: local
  dbeaver_config:
    driver: local
